sudo: required
services:
  - docker

before_install:
  - docker build -t prncs/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run prncs/react-test npm test -- --coverage

after_success:
  - docker build -t prncs/multi-client ./client
  - docker build -t prncs/multi-nginx ./nginx
  - docker build -t prncs/multi-server ./server
  - docker build -t prncs/multi-worker ./worker
  # log into docker hub CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to docker hub
  - docker push prncs/multi-client
  - docker push prncs/multi-nginx
  - docker push prncs/multi-server
  - docker push prncs/multi-worker